FROM broadinstitute/gatk:4.4.0.0

MAINTAINER Jason Li <jasonli3@lsu.edu>

LABEL    software="GATK" \ 
    base_image="broadinstitute/gatk:4.4.0.0" \ 
    about.summary="It is a collection of command-line tools for analyzing high-throughput sequencing data with a primary focus on variant discovery." \ 
    about.home="http://www.broadinstitute.org/gatk" \ 
    software.version="4.4.0.0"
    