#%Module

# =====================================================================
# Generated by CAMP (Containerized Application Modulekey Producer)
# Developer: Jason Li (jasonli3@lsu.edu)
# Description:
#       1) This module template is tested with Module Release >= 4.5.2
#          See https://github.com/cea-hpc/modules
#          May not be compatible with different module systems.
#       2) This module template uses shell functions to map executables
#          in container images.
# =====================================================================

# ---------------------------------------------------------------------
# Software specific information
# ---------------------------------------------------------------------

# Conflicts
conflict $modName $conflict

# Module information
module-whatis $whatis
module-version $modVersion

# Singularity options
set SINGULARITY_IMAGE "$singularity_image"
set SINGULARITY_BINDPATHS "$singularity_bindpaths"
set SINGULARITY_FLAGS "$singularity_flags"

# List of commands to overwrite
set cmds {
$cmds_dummy
}

# Set environment varialbles
$envs

# ---------------------------------------------------------------------
# Module key setup template
# ---------------------------------------------------------------------

# Combine Singularity exec command
set singularity_exec "singularity exec -B $SINGULARITY_BINDPATHS $SINGULARITY_FLAGS --pwd \$PWD $SINGULARITY_IMAGE"

# Overwrite the list of commands upon loading
if { [ module-info mode load ] } {
    if { [ module-info shelltype csh ] } {
        foreach cmd $cmds {
            puts "alias $cmd $singularity_exec $cmd $*; "
        }
    } elseif { [ module-info shelltype sh ] } {
        foreach cmd $cmds {
            puts "$cmd () {"
            puts "    $singularity_exec $cmd $@"
            puts "}"
            #puts "export -f $cmd"
        }
    }
}

# Unset commands upon unloading
if { [ module-info mode unload ] } {
    if { [ module-info shelltype csh ] } {
        foreach cmd $cmds {
            puts "unalias $cmd;"
        }
    } elseif { [ module-info shelltype sh ] } {
        foreach cmd $cmds {
            puts "unset -f $cmd"
        }
    }
}

# For "module help" and "module load"
if { [ module-info mode help ] || [ module-info mode load ] || [ module-info mode display ] } {
    puts stderr "
\[ Help information \]

1. This module only works on computing nodes (not available on head nodes). Make sure you start a job!

2. Below executables are available:
$cmds"
}
proc ModulesHelp {} {
}
