#%Module

# =====================================================================
# Generated by CAMP (Containerized Application Modulekey Producer)
# Developer: Jason Li (jasonli3@lsu.edu)
# Description: This template is for MPI-enabled software packages.
#              Will generate wrappers in user's /work directory.
# =====================================================================

# ---------------------------------------------------------------------
# Software specific information
# ---------------------------------------------------------------------

# Conflicts
conflict $modName $conflict

# Module information
module-whatis $whatis
module-version $modVersion

# Singularity options
set SINGULARITY_IMAGE "$singularity_image"
set SINGULARITY_BINDPATHS "$singularity_bindpaths"
set SINGULARITY_FLAGS "$singularity_flags"

# List of commands to overwrite
set cmds {
$cmds_dummy
}

# Set environment varialbles
$envs

# ---------------------------------------------------------------------
# Module key setup
# ---------------------------------------------------------------------

# Set wrapper paths
puts "mkdir /work/\$USER/.modulebin/$modName/$modVersion -p; "
prepend-path PATH /work/$env(USER)/.modulebin/$modName/$modVersion

# Combine Singularity exec command
set singularity_exec "singularity exec -B $SINGULARITY_BINDPATHS $SINGULARITY_FLAGS --pwd \$PWD $SINGULARITY_IMAGE"

# Create wrapper directory and write wrappers there
if { [ module-info mode load ] } {
    if { [ module-info shelltype csh ] } {
        foreach cmd $cmds {
            puts "echo '#\\!/bin/'`echo \$0 | sed 's|.*/||; s|.*-||'` > /work/\$USER/.modulebin/$modName/$modVersion/$cmd;"
            puts "echo '$singularity_exec $cmd $*' >> /work/\$USER/.modulebin/$modName/$modVersion/$cmd;"
            puts "chmod u+x /work/\$USER/.modulebin/$modName/$modVersion/$cmd;"
        }
        puts "rehash"
    } elseif { [ module-info shelltype sh ] } {
        foreach cmd $cmds {
            puts "echo '#!/bin/'`echo \$0 | sed 's|.*/||; s|.*-||'` > /work/\$USER/.modulebin/$modName/$modVersion/$cmd;"
            puts "echo '$singularity_exec $cmd $@' >> /work/\$USER/.modulebin/$modName/$modVersion/$cmd;"
            puts "chmod u+x /work/\$USER/.modulebin/$modName/$modVersion/$cmd;"
        }
    }
}

# Currently, wrappers will not be deleted to avoid unwanted issues.

# For "module help" and "module load"
if { [ module-info mode help ] || [ module-info mode load ] || [ module-info mode display ] } {
    puts stderr "
\[ Help information \]

1. This module only works on computing nodes (not available on head nodes). Make sure you start a job!

2. Below executables are available:
$cmds
"
}
proc ModulesHelp {} {
}
