#%Module

# =====================================================================
# Generated by CAMP (Containerized Application Modulekey Producer)
# Developer: Jason Li (jasonli3@lsu.edu)
# Description: 
#       1) This module template is compatible with:
#            - Environment Modules >= 4.5.2. 
#               See https://github.com/cea-hpc/modules
#            - Lmod >= 8.7.34. 
#               See https://github.com/TACC/Lmod
#          May not be compatible with different module systems.
#       2) This module template uses shell functions to map executables
#          in container images. 
#          (An older implementation. No long in use)
# =====================================================================


# ---------------------------------------------------------------------
# Software specific information
# ---------------------------------------------------------------------

# Module information
module-whatis Name: $modName
module-whatis Version: $modVersion
module-whatis Description: $whatis

# Singularity options
set SINGULARITY_IMAGE "$singularity_image"
set SINGULARITY_BINDPATHS "$singularity_bindpaths"
set SINGULARITY_FLAGS "$singularity_flags"

# Conflicts
conflict $modName $conflict

# List of commands to overwrite
set CMDS {
$cmds_dummy
}

# Set environment varialbles
$envs

# ---------------------------------------------------------------------
# Module key setup
# ---------------------------------------------------------------------

# Combine Singularity exec command
set SINGULARITY_EXEC "singularity exec -B $SINGULARITY_BINDPATHS $SINGULARITY_FLAGS --pwd \$PWD $SINGULARITY_IMAGE"

# Overwrite the list of commands upon loading
if { [ module-info mode load ] } {
    if { [ module-info shelltype csh ] } {
        foreach cmd $CMDS {
            puts "alias $cmd $SINGULARITY_EXEC $cmd $*; "
        }
    } elseif { [ module-info shelltype sh ] } {
        foreach cmd $CMDS {
            puts "$cmd () {"
            puts "    $SINGULARITY_EXEC $cmd $@"
            puts "}"
            #puts "export -f $cmd"
        }
    }
}

# Unset commands upon unloading
if { [ module-info mode unload ] } {
    if { [ module-info shelltype csh ] } {
        foreach cmd $CMDS {
            puts "unalias $cmd;"
        }
    } elseif { [ module-info shelltype sh ] } {
        foreach cmd $CMDS {
            puts "unset -f $cmd"
        }
    }
}

# Help information
proc ModulesHelp {} {
    global CMDS
    puts stderr "

\[ Help information \]

1. This module only works on computing nodes (not available on head nodes). Make sure you start a job!

2. Below executables are available:
$CMDS"
}
if { [ module-info mode load ] } {
    ModulesHelp
}
