FROM trinityrnaseq/trinityrnaseq:2.15.1

MAINTAINER Jason Li <jasonli3@lsu.edu>

LABEL    software="Jellyfish" \ 
    base_image="trinityrnaseq/trinityrnaseq:2.15.1" \ 
    container="Trinity" \ 
    about.summary="A fast multi-threaded k-mer counter. (This software is included in Trinity 2.15.1)" \ 
    about.home="https://github.com/gmarcais/Jellyfish" \ 
    software.version="2.3.0"

