FROM trinityrnaseq/trinityrnaseq:2.15.1

MAINTAINER Jason Li <jasonli3@lsu.edu>

LABEL    software="Trinity" \ 
    base_image="trinityrnaseq/trinityrnaseq:2.15.1" \ 
    container="Trinity" \ 
    about.summary="Trinity RNA-Seq de novo transcriptome assembly." \ 
    about.home="https://github.com/trinityrnaseq/trinityrnaseq" \ 
    software.version="2.15.1"

