FROM combinelab/salmon:1.10.2

MAINTAINER Jason Li <jasonli3@lsu.edu>

LABEL    software="Salmon" \ 
    base_image="combinelab/salmon:1.10.2" \ 
    container="Salmon" \ 
    about.summary="Highly-accurate & wicked fast transcript-level quantification from RNA-seq reads using selective alignment." \ 
    about.home="https://github.com/COMBINE-lab/salmon" \ 
    software.version="1.10.2"

