FROM ezlabgva/busco:v5.4.7_cv1

MAINTAINER Jason Li <jasonli3@lsu.edu>

LABEL    software="BUSCO & Augustus" \ 
    base_image="ezlabgva/busco:v5.4.7_cv1" \ 
    container="BUSCO" \ 
    about.summary="Based on evolutionarily-informed expectations of gene content of near-universal single-copy orthologs, BUSCO metric is complementary to technical metrics like N50." \ 
    about.home="https://busco.ezlab.org/" \ 
    software.version="5.4.7"

