FROM ncbi/blast:2.14.1

MAINTAINER Jason Li <jasonli3@lsu.edu>

LABEL    software="BLAST" \ 
    base_image="ncbi/blast:2.14.1" \ 
    container="BLAST" \ 
    about.summary="BLAST finds regions of similarity between biological sequences. The program compares nucleotide or protein sequences to sequence databases and calculates the statistical significance." \ 
    about.home="https://blast.ncbi.nlm.nih.gov/blast/Blast.cgi" \ 
    software.version="2.14.1"

