FROM snakemake/snakemake:v7.32.4

MAINTAINER Jason Li <jasonli3@lsu.edu>

LABEL    software="Snakemake" \ 
    base_image="snakemake/snakemake:v7.32.4" \ 
    about.summary="The Snakemake workflow management system is a tool to create reproducible and scalable data analyses." \ 
    about.home="https://snakemake.readthedocs.io/" \ 
    software.version="7.32.4"

