FROM staphb/samtools:1.18

MAINTAINER Jason Li <jasonli3@lsu.edu>

LABEL    software="samtools" \ 
    base_image="staphb/samtools:1.18" \ 
    container="Samtools" \ 
    about.summary="Tools (written in C using htslib) for manipulating next-generation sequencing data." \ 
    about.home="https://github.com/samtools/samtools" \ 
    software.version="1.18"

