FROM ezlabgva/busco:v5.4.7_cv1

MAINTAINER Jason Li <jasonli3@lsu.edu>

LABEL    software="Augustus" \ 
    base_image="ezlabgva/busco:v5.4.7_cv1" \ 
    container="BUSCO" \ 
    about.summary="AUGUSTUS is a program to find genes and their structures in one or more genomes. (This software is included in BUSCO 5.4.7 container)" \ 
    about.home="https://busco.ezlab.org/" \ 
    software.version="3.5.0"

