FROM quay.io/biocontainers/hisat2:2.2.1--hdbdd923_6

MAINTAINER Jason Li <jasonli3@lsu.edu>

LABEL    software="HISAT2" \ 
    base_image="quay.io/biocontainers/hisat2:2.2.1--hdbdd923_6" \ 
    about.summary="HISAT2 is a fast and sensitive alignment program for mapping next-generation sequencing reads (both DNA and RNA) to a population of human genomes as well as to a single reference genome." \ 
    about.home="https://daehwankimlab.github.io/hisat2/" \ 
    software.version="2.2.1"

