FROM quay.io/biocontainers/bowtie2:2.5.1--py310h8d7afc0_0

MAINTAINER Jason Li <jasonli3@lsu.edu>

LABEL    software="Bowtie2" \ 
    base_image="quay.io/biocontainers/bowtie2:2.5.1--py310h8d7afc0_01" \ 
    container="Bowtie2" \ 
    about.summary="A fast and sensitive gapped read aligner." \ 
    about.home="https://github.com/BenLangmead/bowtie2" \ 
    software.version="2.5.1"

